# For more information: https://laravel.com/docs/sail
version: '3'
services:
  app:
    build:
      context: ./docker/8.1
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.1/app
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
  mysql:
    image: 'mysql/mysql-server:8.0'
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    command: redis-server --appendonly yes --replica-read-only no
  swagger:
    image: swaggerapi/swagger-ui:v4.2.1
    restart: always
    ports:
      - "9000:8080"
    volumes:
      - './openapi.yml:/usr/local/openapi.yml'
    environment:
      SWAGGER_JSON: /usr/local/openapi.yml
    networks:
      - sail
  nginx:
    image: nginx:1.23.2-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl/www/:/var/www/certbot/
      - ./ssl/conf/:/etc/letsencrypt/
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - sail
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:v1.32.0
    restart: unless-stopped
    volumes:
      - ./ssl/www/:/var/www/certbot/
      - ./ssl/conf/:/etc/letsencrypt/
    networks:
      - sail
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  phpmyadmin:
    image: phpmyadmin:5.1.1
    restart: always
    ports:
      - 5000:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
